services:
  rabbit:
    image: rabbitmq:4.0-rc-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq    
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge